title: BAGS
email: 474benjaminchen@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Documentation for a bias aware gridsearchCV repo.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  474benjaminchen

# Build settings
theme: just-the-docs
plugins:
  - jekyll-feed
