detailed_rfc_params:
  n_estimators: 
    - 50
    - 100
    - 200
    - 500
  max_depth: 
    - 20
    - 40
    - 50
    - None
  min_samples_split: 
    - 2
    - 5
    - 10
  min_samples_leaf: 
    - 2
    - 5
    - 10
  bootstrap: 
    - True
    - False
  criterion: 
    - 'gini'
    - 'entropy'
  max_leaf_nodes:
    - 20
    - 30
    - 40
    - 50
    - None
  class_weight:
    - None
    - 'balanced'
    - 'balanced_subsample'

estimator_rfc_params:
    n_estimators:
    - 10
    - 50
    - 100
    - 200
    - 500

depth_rfc_params:
    max_depth: 
    - 10
    - 20
    - 30
    - 40
    - 50
    - None

leaf_rfc_params:
    max_leaf_nodes:
    - 10
    - 20
    - 30
    - 40
    - 50
    - None

